# Generated by Django 3.0.3 on 2020-04-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': (('input_datafile', 'Can upload datafile'), ('input_form', 'Can submit form'), ('view_forms', 'Can view forms'), ('generate_reports', 'Can generate reports'), ('manage_app', 'Can manage application'), ('view_logs', 'Can view log files'), ('edit_data', 'Can edit data'), ('export_data', 'Can export data'), ('view_dashboard', 'Can view dashboard'), ('prestatiemeting', 'Can execute a prestatiemeting'))},
        ),
    ]
