language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# services that are required to run
services:
  - mysql

# install required dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python manage.py collectstatic
  - python manage.py test

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: release