language: python

python:
- '3.6'
- '3.7'
- '3.8'

services:
- mysql

before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
    -in .travis/id_rsa.enc -out .travis/id_rsa -d

install:
- pip install -r requirements.txt

script:
- python manage.py collectstatic
- python manage.py test

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/scripts/deploy.sh
  on:
    branch: release
