# Generated by Django 3.0.3 on 2020-05-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('number_addition', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('last_filled', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('allow_explanation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldMultipleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Opdrachtgever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpdrachtgeverContactPersoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prestatiemeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('filled_on', models.DateTimeField(null=True)),
                ('filled_og', models.DateTimeField(null=True)),
                ('excel_file', models.FileField(null=True, upload_to='prestatiemetingen/')),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingGradation',
            fields=[
                ('letter', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingOpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingQuestion',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('about', models.CharField(choices=[('OG', 'Opdrachtgever'), ('ON', 'Opdrachtnemer')], max_length=2)),
                ('description', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_amount', models.IntegerField(default=1)),
                ('opdrachtgever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Opdrachtgever')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActiviteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Sap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(blank=True, max_length=100, null=True)),
                ('wbs_element', models.CharField(blank=True, max_length=100, null=True)),
                ('objectomschrijving', models.CharField(blank=True, max_length=100, null=True)),
                ('kost_soort', models.CharField(blank=True, max_length=100, null=True)),
                ('omschrijving', models.CharField(blank=True, max_length=255, null=True)),
                ('personeelsnummer', models.CharField(blank=True, max_length=100, null=True)),
                ('naam_kost_soort', models.CharField(blank=True, max_length=100, null=True)),
                ('achternaam_voornaam', models.CharField(blank=True, max_length=100, null=True)),
                ('per', models.IntegerField(blank=True, null=True)),
                ('aan_afw', models.CharField(blank=True, max_length=100, null=True)),
                ('parprs', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_datum', models.DateField(blank=True, null=True)),
                ('boek_datum', models.DateField(blank=True, null=True)),
                ('hoeveelheid_totaal', models.FloatField(blank=True, null=True)),
                ('he', models.CharField(blank=True, max_length=100, null=True)),
                ('waarde_co_valuta', models.FloatField(blank=True, null=True)),
                ('omschrijving2', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('jaar', models.CharField(blank=True, max_length=255, null=True)),
                ('maand', models.CharField(blank=True, max_length=255, null=True)),
                ('week', models.CharField(blank=True, max_length=255, null=True)),
                ('surcharge', models.CharField(blank=True, max_length=255, null=True)),
                ('overhead', models.CharField(blank=True, max_length=255, null=True)),
                ('besteltekst', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ultimo',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code_contract', models.CharField(blank=True, max_length=30, null=True)),
                ('voortgangsstatus', models.CharField(blank=True, max_length=30, null=True)),
                ('omschrijving_jobsoort', models.CharField(blank=True, max_length=40, null=True)),
                ('sap_nr', models.CharField(blank=True, max_length=30, null=True)),
                ('vervolgjob_van', models.CharField(blank=True, max_length=30, null=True)),
                ('omschrijving', models.TextField(blank=True, null=True)),
                ('code_complex', models.CharField(blank=True, max_length=30, null=True)),
                ('code_object', models.CharField(blank=True, max_length=30, null=True)),
                ('omschrijving_object', models.CharField(blank=True, max_length=50, null=True)),
                ('storingsnummer', models.CharField(blank=True, max_length=50, null=True)),
                ('melddatum', models.DateTimeField(blank=True, null=True)),
                ('gepl_startdatum', models.DateTimeField(blank=True, null=True)),
                ('vertrektijd_thuis', models.DateTimeField(blank=True, null=True)),
                ('aankomsttijd', models.DateTimeField(blank=True, null=True)),
                ('functioneel_herstel_tijd', models.DateTimeField(blank=True, null=True)),
                ('gereedmeldtijd', models.DateTimeField(blank=True, null=True)),
                ('vertrektijd', models.DateTimeField(blank=True, null=True)),
                ('aankomsttijd_thuis', models.DateTimeField(blank=True, null=True)),
                ('medewerker', models.CharField(blank=True, max_length=30, null=True)),
                ('code_installatie', models.CharField(blank=True, max_length=30, null=True)),
                ('code_installatie2', models.CharField(blank=True, max_length=25, null=True)),
                ('installatie', models.TextField(blank=True, null=True)),
                ('medewerker2', models.CharField(blank=True, max_length=40, null=True)),
                ('meldtext', models.TextField(blank=True, null=True)),
                ('functiehersteltijd_voor', models.DateTimeField(blank=True, null=True)),
                ('streefdatum_gereed_voor', models.DateTimeField(blank=True, null=True)),
                ('info_tekst', models.TextField(blank=True, null=True)),
                ('storingsoorzaak', models.CharField(blank=True, max_length=100, null=True)),
                ('omschrijving_contract', models.CharField(blank=True, max_length=100, null=True)),
                ('prioriteit', models.CharField(blank=True, max_length=40, null=True)),
                ('vestiging', models.CharField(blank=True, max_length=10, null=True)),
                ('vakgroep', models.CharField(blank=True, max_length=50, null=True)),
                ('leverancier', models.CharField(blank=True, max_length=60, null=True)),
                ('stremming_ja', models.BooleanField(blank=True, null=True)),
                ('scheepvaart', models.BooleanField(blank=True, null=True)),
                ('landverkeer', models.BooleanField(blank=True, null=True)),
                ('geplande_stremming', models.BooleanField(blank=True, null=True)),
                ('stremming_van', models.DateTimeField(blank=True, null=True)),
                ('stremming_tot', models.DateTimeField(blank=True, null=True)),
                ('stremmingsduur', models.FloatField(blank=True, null=True)),
                ('geplande_uren', models.CharField(blank=True, max_length=30, null=True)),
                ('geaccepteerd', models.CharField(blank=True, max_length=5, null=True)),
                ('code_medewerker', models.CharField(blank=True, max_length=10, null=True)),
                ('medewerker3', models.CharField(blank=True, max_length=30, null=True)),
                ('datum_geaccepteerd', models.DateTimeField(blank=True, null=True)),
                ('meerwerk', models.BooleanField(blank=True, null=True)),
                ('code_document', models.CharField(blank=True, max_length=10, null=True)),
                ('omschrijving_document', models.CharField(blank=True, max_length=100, null=True)),
                ('code_jobplan', models.CharField(blank=True, max_length=10, null=True)),
                ('omschrijving_jobplan', models.CharField(blank=True, max_length=100, null=True)),
                ('omschrijving_job', models.TextField(blank=True, null=True)),
                ('werkinstructie', models.TextField(blank=True, null=True)),
                ('observatietekst', models.TextField(blank=True, null=True)),
                ('onderzoektekst', models.TextField(blank=True, null=True)),
                ('conclusietekst', models.TextField(blank=True, null=True)),
                ('uitgevoerde_werkzaamheden', models.TextField(blank=True, null=True)),
                ('controletekst', models.TextField(blank=True, null=True)),
                ('opmerking_advies', models.TextField(blank=True, null=True)),
                ('afbeelding', models.CharField(blank=True, max_length=100, null=True)),
                ('afbeelding2', models.CharField(blank=True, max_length=100, null=True)),
                ('afbeelding3', models.CharField(blank=True, max_length=100, null=True)),
                ('afbeelding4', models.CharField(blank=True, max_length=100, null=True)),
                ('gewerkte_uren', models.FloatField(blank=True, null=True)),
                ('installatie2', models.CharField(blank=True, max_length=100, null=True)),
                ('installatie3', models.CharField(blank=True, max_length=100, null=True)),
                ('code_installatie3', models.CharField(blank=True, max_length=30, null=True)),
                ('gevalideerd_door_rws', models.BooleanField(blank=True, null=True)),
                ('ontvangen_rws', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('goal', models.TextField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('INR', 'Inrichting'), ('ONT', 'Ontwerp'), ('UIT', 'Uitvoer'), ('OPL', 'Oplevering'), ('OVG', 'Overig')], max_length=3)),
                ('description', models.TextField()),
                ('activities', models.ManyToManyField(to='data.ProjectActiviteit')),
            ],
        ),
    ]
