# Generated by Django 3.0.3 on 2020-05-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimo',
            name='geplande_stremming',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='gevalideerd_door_rws',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='landverkeer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='meerwerk',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='scheepvaart',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='stremming_ja',
            field=models.BooleanField(),
        ),
    ]
