# Generated by Django 3.0.3 on 2020-03-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimo',
            name='info_tekst',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
