# Generated by Django 3.0.3 on 2020-05-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('vpi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vpis',
            field=models.ManyToManyField(blank=True, to='vpi.VPI'),
        ),
        migrations.AddField(
            model_name='prestatiemetingresult',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingAnswer'),
        ),
        migrations.AddField(
            model_name='prestatiemetingresult',
            name='prestatiemeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Prestatiemeting'),
        ),
        migrations.AddField(
            model_name='prestatiemetingresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingQuestion'),
        ),
        migrations.AddField(
            model_name='prestatiemetingquestion',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingTheme'),
        ),
        migrations.AddField(
            model_name='prestatiemetingopenquestion',
            name='prestatiemeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Prestatiemeting'),
        ),
        migrations.AddField(
            model_name='prestatiemetingconfig',
            name='prestatiemeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Prestatiemeting'),
        ),
        migrations.AddField(
            model_name='prestatiemetingconfig',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingQuestion'),
        ),
        migrations.AddField(
            model_name='prestatiemetinganswer',
            name='gradation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingGradation'),
        ),
        migrations.AddField(
            model_name='prestatiemetinganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingQuestion'),
        ),
        migrations.AddField(
            model_name='prestatiemeting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project'),
        ),
        migrations.AddField(
            model_name='prestatiemeting',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestatiemeting_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestatiemeting',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestatiemeting_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdrachtgevercontactpersoon',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Address'),
        ),
        migrations.AddField(
            model_name='opdrachtgevercontactpersoon',
            name='opdrachtgever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Opdrachtgever'),
        ),
        migrations.AddField(
            model_name='opdrachtgever',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Address'),
        ),
        migrations.AddField(
            model_name='formfieldmultiplechoiceanswer',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.FormField'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Form'),
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
