# Generated by Django 3.0.3 on 2020-05-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200512_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VPITarget',
        ),
    ]
