# Generated by Django 3.0.3 on 2020-05-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200514_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimo',
            name='geplande_stremming',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='gevalideerd_door_rws',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='landverkeer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='meerwerk',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='scheepvaart',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='stremming_ja',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
