# Generated by Django 3.0.3 on 2020-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_delete_vpitarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimo',
            name='aankomsttijd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='melddatum',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
