# Generated by Django 3.0.3 on 2020-05-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200514_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='combined_vpis',
        ),
    ]
