# Generated by Django 3.0.3 on 2020-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_project_combined_vpis'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.IntegerField(default=1),
        ),
    ]
