# Generated by Django 3.0.3 on 2020-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200513_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimo',
            name='aankomsttijd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultimo',
            name='melddatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
