# Generated by Django 3.0.3 on 2020-05-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
    ]
