# Generated by Django 3.0.3 on 2020-04-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200330_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('measuring_unit', models.CharField(max_length=20)),
                ('formula', models.CharField(blank=True, max_length=200, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.CharField(max_length=10)),
                ('yellow', models.CharField(max_length=20)),
                ('red', models.CharField(max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.models.project')),
                ('vpi_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.VPI')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('goal', models.TextField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.models.project')),
            ],
        ),
    ]
