# Generated by Django 3.0.3 on 2020-05-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_prestatiemeting_excel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='combined_vpis',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vpis',
        ),
        migrations.AlterField(
            model_name='prestatiemeting',
            name='excel_file',
            field=models.FileField(null=True, upload_to='prestatiemetingen/'),
        ),
    ]
