# Generated by Django 3.0.3 on 2020-05-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0007_projectvpi'),
        ('data', '0010_auto_20200514_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='combined_vpis',
            field=models.ManyToManyField(blank=True, to='vpi.CombinedVPI'),
        ),
        migrations.AddField(
            model_name='project',
            name='vpis',
            field=models.ManyToManyField(blank=True, to='vpi.VPI'),
        ),
    ]
