# Generated by Django 3.0.3 on 2020-04-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_project_projectgoal_target_vpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vpi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.VPI')),
            ],
        ),
        migrations.CreateModel(
            name='VPITarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.CharField(max_length=10)),
                ('yellow', models.CharField(max_length=20)),
                ('red', models.CharField(max_length=20)),
                ('project_goal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.ProjectGoal')),
                ('vpi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.VPI')),
            ],
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
