# Generated by Django 3.0.3 on 2020-05-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200514_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultimo',
            name='melddatum',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
