# Generated by Django 3.0.3 on 2020-04-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200422_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='vpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.VPI'),
        ),
    ]
