# Generated by Django 3.0.3 on 2020-04-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200422_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpi',
            options={'permissions': (('can_view_dashboard', 'View dashboard'),)},
        ),
    ]
