# Generated by Django 3.0.3 on 2020-04-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20200423_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpi',
            options={'permissions': (('can_view_dashboard', 'Can view dashboard'),)},
        ),
    ]
