# Generated by Django 3.0.3 on 2020-04-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20200423_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpi',
            options={'permissions': (('view_dashboard', 'Can view dashboard'),)},
        ),
    ]
