# Generated by Django 3.0.3 on 2020-04-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20200423_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpi',
            options={},
        ),
    ]
