# Generated by Django 3.0.3 on 2020-04-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20200423_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgoal',
            name='project',
        ),
        migrations.RemoveField(
            model_name='value',
            name='vpi',
        ),
        migrations.RemoveField(
            model_name='vpitarget',
            name='project_goal',
        ),
        migrations.RemoveField(
            model_name='vpitarget',
            name='vpi',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectGoal',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.DeleteModel(
            name='VPI',
        ),
        migrations.DeleteModel(
            name='VPITarget',
        ),
    ]
