# Generated by Django 3.0.3 on 2020-04-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0008_project_projectgoal_value_vpi_vpitarget'),
        ('data', '0017_auto_20200424_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestatiemeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('gradation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingQuestion',
            fields=[
                ('question_number', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('theme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingOpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('prestatiemeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Prestatiemeting')),
            ],
        ),
        migrations.CreateModel(
            name='PrestatiemetingBeoordeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingAnswer')),
                ('prestatiemeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Prestatiemeting')),
            ],
        ),
        migrations.AddField(
            model_name='prestatiemetinganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingQuestion'),
        ),
    ]
