# Generated by Django 3.0.3 on 2020-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20200424_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestatiemetingGradation',
            fields=[
                ('letter', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('gradation', models.CharField(max_length=10)),
            ],
        ),
    ]
