# Generated by Django 3.0.3 on 2020-04-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_prestatiemetinggradation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestatiemetinganswer',
            name='gradation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingGradation'),
        ),
    ]
