# Generated by Django 3.0.3 on 2020-04-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20200424_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatiemetingquestion',
            name='prestatiemeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Prestatiemeting'),
        ),
    ]
