# Generated by Django 3.0.3 on 2020-04-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_prestatiemetingquestion_prestatiemeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestatiemetingquestion',
            name='prestatiemeting',
        ),
    ]
