# Generated by Django 3.0.3 on 2020-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_remove_prestatiemetingquestion_prestatiemeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatiemeting',
            name='questions',
            field=models.ManyToManyField(to='data.PrestatiemetingQuestion'),
        ),
    ]
