# Generated by Django 3.0.3 on 2020-04-24 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0024_form_formfield_formfieldmultiplechoiceanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='user',
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
