# Generated by Django 3.0.3 on 2020-04-28 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20200424_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestatiemetingTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='prestatiemeting',
            name='questions',
        ),
        migrations.AddField(
            model_name='prestatiemeting',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prestatiemetinganswer',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='PrestatiemetingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestatiemeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Prestatiemeting')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingQuestion')),
            ],
        ),
        migrations.AlterField(
            model_name='prestatiemetingquestion',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingTheme'),
        ),
    ]
