# Generated by Django 3.0.3 on 2020-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20200428_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestatiemetingtheme',
            name='theme',
            field=models.CharField(max_length=50),
        ),
    ]
