# Generated by Django 3.0.3 on 2020-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20200428_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestatiemeting',
            old_name='project_number',
            new_name='project',
        ),
    ]
