# Generated by Django 3.0.3 on 2020-04-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20200428_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestatiemetingquestion',
            old_name='question_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='prestatiemeting',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PrestatiemetingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingAnswer')),
                ('prestatiemeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Prestatiemeting')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PrestatiemetingQuestion')),
            ],
        ),
    ]
