# Generated by Django 3.0.3 on 2020-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20200428_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatiemetingquestion',
            name='about',
            field=models.CharField(choices=[('OG', 'Opdrachtgever'), ('ON', 'Opdrachtnemer')], default='OG', max_length=2),
            preserve_default=False,
        ),
    ]
