# Generated by Django 3.0.3 on 2020-04-29 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_prestatiemetingquestion_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatiemetingresult',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 29, 8, 11, 41, 790022)),
        ),
    ]
