# Generated by Django 3.0.3 on 2020-04-29 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_prestatiemetingresult_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestatiemetingresult',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
