# Generated by Django 3.0.3 on 2020-04-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_auto_20200429_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestatiemetingresult',
            name='timestamp',
        ),
    ]
