# Generated by Django 3.0.3 on 2020-04-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_remove_prestatiemetingresult_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatiemetingresult',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
