# Generated by Django 3.0.3 on 2020-04-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_prestatiemetingresult_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatiemetingquestion',
            name='weight',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
