# Generated by Django 3.0.3 on 2020-04-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_prestatiemetingquestion_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatiemetinggradation',
            name='score',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
