# Generated by Django 3.0.3 on 2020-05-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_prestatiemetinggradation_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestatiemeting',
            old_name='dateTime',
            new_name='datetime',
        ),
    ]
