# Generated by Django 3.0.3 on 2020-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_auto_20200502_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestatiemeting',
            old_name='datetime',
            new_name='filled_og',
        ),
        migrations.RenameField(
            model_name='prestatiemetinggradation',
            old_name='gradation',
            new_name='description',
        ),
        migrations.AddField(
            model_name='prestatiemeting',
            name='filled_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='PrestatiemetingBeoordeling',
        ),
    ]
