# Generated by Django 3.0.3 on 2020-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20200502_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
