# Generated by Django 3.0.3 on 2020-05-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_sap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sap',
            name='aan_afw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='achternaam_voornaam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='besteltekst',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='boek_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='doc_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='doc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='he',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='hoeveelheid_totaal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='jaar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='kost_soort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='maand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='naam_kost_soort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='object',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='objectomschrijving',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='omschrijving',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='omschrijving2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='overhead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='parprs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='personeelsnummer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='surcharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='waarde_co_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='wbs_element',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sap',
            name='week',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
