# Generated by Django 3.0.3 on 2020-05-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0024_project_object_amount'),
        ('data', '0044_auto_20200504_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActiviteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('INR', 'Inrichting'), ('ONT', 'Ontwerp'), ('UIT', 'Uitvoer'), ('OPL', 'Oplevering'), ('OVG', 'Overig')], max_length=3)),
                ('description', models.TextField()),
                ('activities', models.ManyToManyField(to='data.ProjectActiviteit')),
            ],
        ),
    ]
