# Generated by Django 3.0.3 on 2020-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_projectactiviteit_projectfase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactiviteit',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projectactiviteit',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
