# Generated by Django 3.0.3 on 2020-05-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20200505_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfase',
            name='activities',
        ),
        migrations.AddField(
            model_name='projectactiviteit',
            name='project_fase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.ProjectFase'),
            preserve_default=False,
        ),
    ]
