# Generated by Django 3.0.3 on 2020-05-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_auto_20200505_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactiviteit',
            name='project_fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.ProjectFase'),
        ),
    ]
