# Generated by Django 3.0.3 on 2020-05-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20200505_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectactiviteit',
            name='project_fase',
        ),
        migrations.AddField(
            model_name='projectfase',
            name='activities',
            field=models.ManyToManyField(to='data.ProjectActiviteit'),
        ),
    ]
