# Generated by Django 3.0.3 on 2020-05-06 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0049_auto_20200505_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatiemeting',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestatiemeting_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestatiemeting',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestatiemeting_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
