# Generated by Django 3.0.3 on 2020-05-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20200506_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatiemetingquestion',
            name='description',
            field=models.CharField(default='placeholder', max_length=30),
            preserve_default=False,
        ),
    ]
