# Generated by Django 3.0.3 on 2020-05-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_prestatiemetingquestion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestatiemetingquestion',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
