from django.contrib.admin.utils import unquote
from django.contrib.auth.decorators import permission_required, login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from data.helpers.excel import prestatiemeting_report
from data.models.prestatiemeting import Prestatiemeting, PrestatiemetingResult, PrestatiemetingQuestion
from data.models.project import Project
from vpi.models import VPI, VPIValue
from .models import Report, Dashboard, DashboardObject


@login_required
@permission_required('perms.view_dashboard', login_url='login')
def general_dashboard(request, dashboard_id):
    """
    A general dashboard view defined in the database.
    @param request: http request object
    @param dashboard_id: id of the dashboard to be shown.
    @return: dashboard view
    """
    dashboard = get_object_or_404(Dashboard, id=dashboard_id)
    print(VPIValue.objects.select_subclasses())
    return render(request, 'dashboard/dashboard.html', {'dashboard': dashboard})


@login_required
@permission_required('perms.view_dashboard', login_url='login')
def project_dashboard(request, project_number):
    """
    Dashboard view for specific projects
    @param request: http request object
    @param project_number: id of the project.
    @return: dashboard view
    """
    project_number = unquote(project_number)
    dashboard, created = Dashboard.objects.get_or_create(project_id=project_number,
                                                         defaults={'name': f'autogenerated {project_number}'})

    # Add some default dashboard objects to newly created dashboard
    if created:
        DashboardObject.objects.get_or_create(dashboard=dashboard, vpi_id=1, chart_type=DashboardObject.CARD,
                                              col_width=3, row_number=1, row_order=1)
        DashboardObject.objects.get_or_create(dashboard=dashboard, vpi_id=13, chart_type=DashboardObject.PIE,
                                              col_width=4, row_number=2, row_order=1)

    return render(request, 'dashboard/dashboard.html', {'dashboard': dashboard})


@login_required
@permission_required('perms.generate_reports')
def reports(request):
    """
    Overview view of available reports
    @param request: http request object
    @return: reports view
    """
    reports = Report.objects.all()
    projects = Project.objects.all()

    return render(request, 'dashboard/reports.html', {'reports': reports,
                                                      'projects': projects})


@login_required
@permission_required('perms.generate_reports')
def reports_detail(request):
    """
    Detail view for individual reports
    @param request: http request object
    @return: detail report view
    """
    if request.POST:
        pm = Prestatiemeting.objects.get(project_id=request.POST.get('project_select'),
                                         number=request.POST.get('pm_select'))

        output = prestatiemeting_report(pm.id)
        output.seek(0)

        filename = 'prestatiemeting_resultaten.xlsx'
        response = HttpResponse(
            output,
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = 'attachment; filename=%s' % filename

        return response
