# Generated by Django 3.0.3 on 2020-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vpi', '0018_auto_20200430_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpis', models.ManyToManyField(to='vpi.VPI')),
            ],
        ),
    ]
