# Generated by Django 3.0.3 on 2020-05-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('vpi', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Project'),
        ),
        migrations.AddField(
            model_name='dashboardobject',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Dashboard'),
        ),
        migrations.AddField(
            model_name='dashboardobject',
            name='vpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPI'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardobject',
            unique_together={('dashboard', 'row_number', 'row_order')},
        ),
    ]
