# Generated by Django 3.0.3 on 2020-05-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200514_1416'),
        ('vpi', '0008_delete_projectvpi'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('vpis', models.ManyToManyField(to='vpi.VPI')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDashboard',
            fields=[
                ('generaldashboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.GeneralDashboard')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
            ],
            bases=('dashboard.generaldashboard',),
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
