# Generated by Django 3.0.3 on 2020-05-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0004_delete_combinedvpi'),
        ('data', '0004_remove_project_combined_vpis'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('area', 'Area chart'), ('card', 'Card'), ('bar', 'Bar chart'), ('pie', 'Pie chart')], max_length=10)),
                ('col_width', models.IntegerField()),
                ('order', models.IntegerField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Dashboard')),
                ('vpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPI')),
            ],
        ),
        migrations.DeleteModel(
            name='GeneralDashboard',
        ),
        migrations.DeleteModel(
            name='ProjectDashboard',
        ),
    ]
