# Generated by Django 3.0.3 on 2020-06-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200525_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_by', models.CharField(max_length=100)),
                ('dashboard_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DashboardObject')),
            ],
        ),
        migrations.CreateModel(
            name='FilterObjectBoolean',
            fields=[
                ('filterobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.FilterObject')),
                ('filter_value', models.BooleanField()),
            ],
            bases=('dashboard.filterobject',),
        ),
        migrations.CreateModel(
            name='FilterObjectDateTime',
            fields=[
                ('filterobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.FilterObject')),
                ('filter_value', models.DateTimeField()),
            ],
            bases=('dashboard.filterobject',),
        ),
        migrations.CreateModel(
            name='FilterObjectString',
            fields=[
                ('filterobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.FilterObject')),
                ('filter_value', models.CharField(max_length=100)),
            ],
            bases=('dashboard.filterobject',),
        ),
    ]
