# Generated by Django 3.0.3 on 2020-05-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200515_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardobject',
            name='row_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
