# Generated by Django 3.0.3 on 2020-05-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboardobject_row_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardobject',
            old_name='order',
            new_name='row_order',
        ),
    ]
