# Generated by Django 3.0.3 on 2020-06-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_filterobject_filterobjectboolean_filterobjectdatetime_filterobjectstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterobjectboolean',
            name='filterobject_ptr',
        ),
        migrations.RemoveField(
            model_name='filterobjectdatetime',
            name='filterobject_ptr',
        ),
        migrations.RemoveField(
            model_name='filterobjectstring',
            name='filterobject_ptr',
        ),
        migrations.DeleteModel(
            name='FilterObject',
        ),
        migrations.DeleteModel(
            name='FilterObjectBoolean',
        ),
        migrations.DeleteModel(
            name='FilterObjectDateTime',
        ),
        migrations.DeleteModel(
            name='FilterObjectString',
        ),
    ]
