# Generated by Django 3.0.3 on 2020-05-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0028_vpi_label'),
        ('dashboard', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpi.Project'),
        ),
    ]
