# Generated by Django 3.0.3 on 2020-05-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200516_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardobject',
            name='decimal_amount',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dashboardobject',
            name='chart_type',
            field=models.CharField(choices=[('area', 'Area chart'), ('card', 'Card'), ('bar', 'Bar chart'), ('pie', 'Pie chart'), ('table', 'Table')], max_length=10),
        ),
    ]
