# Generated by Django 3.0.3 on 2020-05-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200516_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardobject',
            name='decimal_amount',
        ),
    ]
