# Generated by Django 3.0.3 on 2020-05-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_dashboardobject_decimal_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardobject',
            unique_together={('dashboard', 'row_number', 'row_order')},
        ),
    ]
