# Generated by Django 3.0.3 on 2020-05-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200516_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardobject',
            name='chart_type',
            field=models.CharField(choices=[('area', 'Area chart'), ('card', 'Card'), ('bar', 'Bar chart'), ('pie', 'Pie chart'), ('table', 'Table'), ('progress', 'Progress')], max_length=10),
        ),
    ]
