# Generated by Django 3.0.3 on 2020-03-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('measuring_unit', models.CharField(max_length=20)),
                ('formula', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('pi_type', models.CharField(max_length=20)),
                ('default_value_calc', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performance_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_generator.PerformanceIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.IntegerField()),
                ('yellow', models.IntegerField()),
                ('red', models.IntegerField()),
                ('project_number', models.IntegerField(null=True)),
                ('performance_indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pi_generator.PerformanceIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='SourceForPerformanceIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_generator.PerformanceIndicator')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_generator.Source')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
                ('performance_indicator', models.ManyToManyField(to='pi_generator.PerformanceIndicator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_generator.Project')),
            ],
        ),
    ]
