# Generated by Django 3.0.3 on 2020-03-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='project_number',
        ),
        migrations.AddField(
            model_name='performanceindicator',
            name='sources',
            field=models.ManyToManyField(to='pi_generator.Source'),
        ),
        migrations.AlterField(
            model_name='performanceindicator',
            name='formula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='SourceForPerformanceIndicator',
        ),
    ]
