# Generated by Django 3.0.3 on 2020-03-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi_generator', '0002_auto_20200306_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='project',
            field=models.ForeignKey(default='P00001', on_delete=django.db.models.deletion.CASCADE, to='pi_generator.Project'),
            preserve_default=False,
        ),
    ]
