# Generated by Django 3.0.3 on 2020-03-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi_generator', '0003_target_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pi_generator.Project'),
        ),
    ]
