# Generated by Django 3.0.3 on 2020-05-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('measuring_unit', models.CharField(blank=True, max_length=20)),
                ('formula', models.CharField(blank=True, max_length=200, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('chart_type', models.CharField(choices=[('AC', 'Area chart'), ('CA', 'Card'), ('BC', 'Bar chart'), ('PC', 'Pie chart')], max_length=2)),
                ('label', models.CharField(max_length=20)),
                ('function', models.CharField(blank=True, max_length=30, null=True)),
                ('has_subset', models.BooleanField(default=False)),
                ('decimal_amount', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='VPIValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPI')),
            ],
        ),
        migrations.CreateModel(
            name='VPITarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
                ('is_better', models.CharField(choices=[('lower', 'Lower'), ('higher', 'Higher')], max_length=6)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
                ('vpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPI')),
            ],
        ),
    ]
