# Generated by Django 3.0.3 on 2020-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpi',
            name='method',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vpi',
            name='label',
            field=models.CharField(max_length=20),
        ),
    ]
