# Generated by Django 3.0.3 on 2020-05-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0002_auto_20200512_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpi',
            name='default_measure',
            field=models.CharField(choices=[('avg', 'Average'), ('last', 'Last'), ('first', 'First')], default='avg', max_length=10),
            preserve_default=False,
        ),
    ]
