# Generated by Django 3.0.3 on 2020-05-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0002_auto_20200526_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VPIValueList',
            fields=[
                ('vpivalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpi.VPIValue')),
            ],
            bases=('vpi.vpivalue',),
        ),
        migrations.AlterField(
            model_name='vpidetailconfig',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line chart'), ('bar', 'Bar chart')], max_length=10),
        ),
        migrations.DeleteModel(
            name='VPIValueBoolean',
        ),
        migrations.AddField(
            model_name='listvalue',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPIValueList'),
        ),
    ]
