# Generated by Django 3.0.3 on 2020-06-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0003_auto_20200526_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FilterObjectBoolean',
            fields=[
                ('filterobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpi.FilterObject')),
                ('filter_value', models.BooleanField()),
            ],
            bases=('vpi.filterobject',),
        ),
        migrations.CreateModel(
            name='FilterObjectDateTime',
            fields=[
                ('filterobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpi.FilterObject')),
                ('filter_value', models.DateTimeField()),
            ],
            bases=('vpi.filterobject',),
        ),
        migrations.CreateModel(
            name='FilterObjectString',
            fields=[
                ('filterobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpi.FilterObject')),
                ('filter_value', models.CharField(max_length=100)),
            ],
            bases=('vpi.filterobject',),
        ),
        migrations.CreateModel(
            name='VPIDetailObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('area', 'Area chart'), ('card', 'Card'), ('bar', 'Bar chart'), ('pie', 'Pie chart'), ('table', 'Table'), ('progress', 'Progress')], max_length=10)),
                ('width', models.IntegerField()),
                ('vpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPI')),
            ],
        ),
        migrations.AddField(
            model_name='filterobject',
            name='vpi_detail_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPIDetailObject'),
        ),
    ]
