# Generated by Django 3.0.3 on 2020-05-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_project_combined_vpis'),
        ('vpi', '0003_auto_20200515_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombinedVPI',
        ),
    ]
