# Generated by Django 3.0.3 on 2020-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0004_auto_20200610_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPISource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
    ]
