# Generated by Django 3.0.3 on 2020-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0004_delete_combinedvpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpi',
            name='decimal_amount',
            field=models.IntegerField(default=2),
        ),
    ]
