# Generated by Django 3.0.3 on 2020-05-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_delete_vpitarget'),
        ('vpi', '0004_auto_20200512_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpi',
            name='default_measure',
            field=models.CharField(choices=[('avg', 'Gemiddlede'), ('last', 'Laatste'), ('first', 'Eerste')], max_length=10),
        ),
        migrations.CreateModel(
            name='VPITarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
                ('is_better', models.CharField(choices=[('lower', 'Lower'), ('higher', 'Higher')], max_length=6)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
                ('vpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPI')),
            ],
        ),
    ]
