# Generated by Django 3.0.3 on 2020-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0005_auto_20200512_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpi',
            name='default_measure',
            field=models.CharField(choices=[('avg', 'Gemiddlede'), ('last', 'Laatste'), ('first', 'Eerste'), ('single', 'Enkele waarde')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vpi',
            name='function',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
