# Generated by Django 3.0.3 on 2020-03-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0005_auto_20200306_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='performance_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.PerformanceIndicator'),
        ),
    ]
