# Generated by Django 3.0.3 on 2020-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0006_vpi_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpisource',
            name='datefield',
            field=models.CharField(default='melddatum', max_length=100),
            preserve_default=False,
        ),
    ]
