# Generated by Django 3.0.3 on 2020-05-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200514_1403'),
        ('vpi', '0006_auto_20200513_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVPI',
            fields=[
                ('vpi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpi.VPI')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Project')),
            ],
            bases=('vpi.vpi',),
        ),
    ]
