# Generated by Django 3.0.3 on 2020-04-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0006_auto_20200306_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgoal',
            name='performance_indicator',
        ),
        migrations.RemoveField(
            model_name='projectgoal',
            name='project',
        ),
        migrations.RemoveField(
            model_name='target',
            name='performance_indicator',
        ),
        migrations.RemoveField(
            model_name='target',
            name='project',
        ),
        migrations.RemoveField(
            model_name='value',
            name='performance_indicator',
        ),
        migrations.DeleteModel(
            name='PerformanceIndicator',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectGoal',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
