# Generated by Django 3.0.3 on 2020-05-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('vpi', '0007_projectvpi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectVPI',
        ),
    ]
