# Generated by Django 3.0.3 on 2020-04-24 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vpi', '0007_auto_20200422_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('goal', models.TextField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpi.Project')),
            ],
        ),
        migrations.CreateModel(
            name='VPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('measuring_unit', models.CharField(max_length=20)),
                ('formula', models.CharField(blank=True, max_length=200, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VPITarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.CharField(max_length=10)),
                ('yellow', models.CharField(max_length=20)),
                ('red', models.CharField(max_length=20)),
                ('project_goal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpi.ProjectGoal')),
                ('vpi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPI')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPI')),
            ],
        ),
    ]
