# Generated by Django 3.0.3 on 2020-06-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0007_vpisource_datefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpisource',
            name='projectfield',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
