# Generated by Django 3.0.3 on 2020-04-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0008_project_projectgoal_value_vpi_vpitarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpi',
            name='chart_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
