# Generated by Django 3.0.3 on 2020-06-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0008_vpisource_projectfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpi',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
