# Generated by Django 3.0.3 on 2020-04-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0009_vpi_chart_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpitarget',
            name='project_goal',
        ),
        migrations.AddField(
            model_name='vpitarget',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpi.Project'),
        ),
    ]
