# Generated by Django 3.0.3 on 2020-04-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0010_auto_20200430_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Value',
            new_name='VPIValue',
        ),
    ]
