# Generated by Django 3.0.3 on 2020-04-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0012_auto_20200430_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpitarget',
            name='vpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.VPI'),
        ),
    ]
