# Generated by Django 3.0.3 on 2020-04-30 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0013_auto_20200430_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('number_addition', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opdrachtgever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OpdrachtgeverContactPersoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpi.Address')),
                ('opdrachtgever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpi.Opdrachtgever')),
            ],
        ),
    ]
