# Generated by Django 3.0.3 on 2020-04-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0014_address_opdrachtgever_opdrachtgevercontactpersoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='opdrachtgever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpi.Opdrachtgever'),
        ),
    ]
