# Generated by Django 3.0.3 on 2020-04-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0015_project_opdrachtgever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdrachtgever',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpi.Address'),
        ),
    ]
