# Generated by Django 3.0.3 on 2020-04-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0016_auto_20200430_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdrachtgever',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpi.Address'),
        ),
        migrations.AlterField(
            model_name='opdrachtgevercontactpersoon',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpi.Address'),
        ),
    ]
