# Generated by Django 3.0.3 on 2020-04-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0017_auto_20200430_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdrachtgevercontactpersoon',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vpi.Address'),
        ),
    ]
