# Generated by Django 3.0.3 on 2020-04-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0019_vpi_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpi',
            name='chart_type',
            field=models.CharField(choices=[('AC', 'Area chart'), ('CA', 'Card'), ('BC', 'Bar chart'), ('PC', 'Pie chart')], default='CA', max_length=2),
            preserve_default=False,
        ),
    ]
