# Generated by Django 3.0.3 on 2020-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0021_auto_20200430_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpi',
            name='measuring_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
