# Generated by Django 3.0.3 on 2020-05-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0023_auto_20200430_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='object_amount',
            field=models.IntegerField(default=1),
        ),
    ]
