# Generated by Django 3.0.3 on 2020-05-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0024_project_object_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpi',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='vpi.Project'),
        ),
    ]
