# Generated by Django 3.0.3 on 2020-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0025_auto_20200506_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpi',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='vpis',
            field=models.ManyToManyField(blank=True, to='vpi.VPI'),
        ),
    ]
