# Generated by Django 3.0.3 on 2020-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpi', '0027_auto_20200506_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpi',
            name='label',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
